services:
  db:
    container_name: db
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./db-data:/var/lib/postgresql/data
    restart: unless-stopped  

  postgrest:
      image: postgrest/postgrest:latest
      ports:
          - 3000:3000
      environment:
          PGRST_DB_URI: postgres://postgres:postgres@db:5432/postgres
          PGRST_DB_ANON_ROLE: anon
          PGRST_DB_SCHEMA: public
      depends_on:
          - db